import { writeFileSync } from 'node:fs';
import { it } from 'vitest';
import { computeFrequencies } from '../src/loshu';

// Regenerates src/data/frequencies.ts:  GEN_FREQ=1 npx vitest run tests/genFrequencies.test.ts
it.skipIf(!process.env.GEN_FREQ)('generate frequency table', () => {
  const table = computeFrequencies(1900, 2025);
  const body = `// GENERATED by tests/genFrequencies.test.ts from the calculation engine. Do not edit by hand.\n// Every calendar date from ${table.from} to ${table.to} counted once (not population-weighted).\nimport type { FrequencyTable } from '../loshu/frequency';\n\nexport const FREQUENCIES: FrequencyTable = ${JSON.stringify(table, null, 2)};\n`;
  writeFileSync('src/data/frequencies.ts', body);
}, 120_000);
